version: '3.9'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data: