from enum import Enum


class Action(Enum):
	CHAIN_REQUEST = 'CHAIN_REQUEST'
	CHAIN_SEND = 'CHAIN_SEND'
	BLOCK_MINED = 'BLOCK_MINED'
	BLOCK_MINING = 'BLOCK_MINING'
	NEW_BLOCK = 'NEW_BLOCK'
	NEW_TRANSACTION = 'NEW_TRANSACTION'
